In [5]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [7]:
#To read a csv file and convert to dataframe
dframe = pd.read_csv('dataread.csv')
dframe

English  Maths  Science  Marathi
0     74.2   63.8     54.0     78.0
1     41.3   58.9     25.0      2.0
2     98.6  102.7     29.9     20.9
3     52.6   23.6     75.4     30.8

LECTURE 27: HTML with Python

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
from pandas import read_html

In [2]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'

In [4]:
dframe_list = pd.io.html.read_html(url)

ImportError: html5lib not found, please install it

LECTURE 28: Excel with Python

In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
xlfile = pd.ExcelFile('MSDS_Original.xlsx', engine = 'openpyxl')

In [4]:
dframe = xlfile.parse('Sheet2')

In [6]:
dframe[0:9]

Sr. No.                                    University Name  Rank  \
0      1.0                             U. Michigan, Ann Arbor   NaN   
1      2.0                     U. Colorado, Boulder, Colorado   NaN   
2      3.0                      U. Oklahoma, Norman, Oklahoma   NaN   
3      4.0                U. Colorado, Fort Collins, Colorado   NaN   
4      5.0                         San Diego State University   NaN   
5      6.0  University of Massachusetts Dartmouth – North ...   NaN   
6      7.0                            George Mason University   NaN   
7      8.0                       DePaul Uni. Chicgo, Illinois   NaN   
8      9.0                      University of Arizona, Tucson   NaN   

   Inst. code Course duratn. SOP LOR Personal Statement  GRE GRE req.  ...  \
0      1839.0          2 yrs   Y   Y                  Y    N      NaN  ...   
1      4841.0          2 yrs   Y   Y                  Y    N      NaN  ...   
2      6879.0    1yr 2months   Y   Y                NaN    N      NaN  ...   
3      4075.0         1 year   Y   Y                NaN    Y      NaN  ...   
4      4682.0            NaN   Y   Y                  N    N      NaN  ...   
5      3786.0            NaN   Y   Y                NaN    Y       NS  ...   
6      5827.0            NaN   Y   Y                NaN    N      NaN  ...   
7      1165.0            NaN   Y   Y                NaN  NaN      NaN  ...   
8      4832.0      1.5 years   Y   Y                  N    N      NaN  ...   

  Unnamed: 24 Unnamed: 25 Unnamed: 26  Unnamed: 27  Unnamed: 28  Unnamed: 29  \
0         NaN         NaN         NaN          NaN          NaN          NaN   
1         NaN         NaN         NaN          NaN          NaN          NaN   
2         NaN         NaN         NaN          NaN          NaN          NaN   
3         NaN         NaN         NaN          NaN          NaN          NaN   
4         NaN         NaN         NaN          NaN          NaN          NaN   
5         NaN         NaN         NaN          NaN          NaN          NaN   
6         NaN         NaN         NaN          NaN          NaN          NaN   
7         NaN         NaN         NaN          NaN          NaN          NaN   
8         NaN         NaN         NaN          NaN          NaN          NaN   

   Unnamed: 30  Unnamed: 31  Unnamed: 32  Unnamed: 33  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN  
5          NaN          NaN          NaN          NaN  
6          NaN          NaN          NaN          NaN  
7          NaN          NaN          NaN          NaN  
8          NaN          NaN          NaN          NaN  

[9 rows x 34 columns]

In [7]:
dframe1 = DataFrame({'ID': {0: 23, 1: 43, 2: 12,
                                 3: 13, 4: 67, 5: 89,
                                 6: 90, 7: 56, 8: 34},
                          'Name': {0: 'Ram', 1: 'Deep',
                                   2: 'Yash', 3: 'Aman',
                                   4: 'Arjun', 5: 'Aditya',
                                   6: 'Divya', 7: 'Chalsea',
                                   8: 'Akash' },
                          'Marks': {0: 89, 1: 97, 2: 45, 3: 78,
                                    4: 56, 5: 76, 6: 100, 7: 87,
                                    8: 81},
                          'Grade': {0: 'B', 1: 'A', 2: 'F', 3: 'C',
                                    4: 'E', 5: 'C', 6: 'A', 7: 'B',
                                    8: 'B'}})

In [8]:
filename = 'Marks card.xlsx'

In [1]:
dframe.to_excel(file_name)

NameError: name 'dframe' is not defined

LECTURE 29: Merging

In [39]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [40]:
dframe1 = DataFrame({'key':['A','A','B','C','C',],'dataset_1':[25,36,96,45,58]})

In [4]:
dframe1

key  dataset_1
0   A         25
1   A         36
2   B         96
3   C         45
4   C         58

In [41]:
dframe2 = DataFrame({'key':['A','B','B','C'],'dataset_2':[82,34,21,19]})

In [6]:
dframe2

key  dataset_2
0   A         82
1   B         34
2   B         21
3   C         19

In [7]:
pd.merge(dframe1,dframe2)

key  dataset_1  dataset_2
0   A         25         82
1   A         36         82
2   B         96         34
3   B         96         21
4   C         45         19
5   C         58         19

In [8]:
pd.merge(dframe1,dframe2,on='key')

key  dataset_1  dataset_2
0   A         25         82
1   A         36         82
2   B         96         34
3   B         96         21
4   C         45         19
5   C         58         19

In [42]:
dframe1.join(dframe2)

ValueError: columns overlap but no suffix specified: Index(['key'], dtype='object')

In [9]:
pd.merge(dframe1,dframe2,on='key',how='left')

key  dataset_1  dataset_2
0   A         25         82
1   A         36         82
2   B         96         34
3   B         96         21
4   C         45         19
5   C         58         19

In [13]:
dframe3 = DataFrame({'key':['B','C','C','D'],'dataset_3':[10,20,30,40]})
dframe3

key  dataset_3
0   B         10
1   C         20
2   C         30
3   D         40

In [14]:
dframe4 = DataFrame({'key':['A','B','C','C'],'dataset_4':[50,60,70,80]})
dframe4

key  dataset_4
0   A         50
1   B         60
2   C         70
3   C         80

In [16]:
pd.merge(dframe3,dframe4,on='key',how='right')

key  dataset_3  dataset_4
0   A        NaN         50
1   B       10.0         60
2   C       20.0         70
3   C       30.0         70
4   C       20.0         80
5   C       30.0         80

In [19]:
pd.merge(dframe3,dframe4,on='key',how='right')

key  dataset_3  dataset_4
0   A        NaN         50
1   B       10.0         60
2   C       20.0         70
3   C       30.0         70
4   C       20.0         80
5   C       30.0         80

In [21]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [27]:
dframeA = DataFrame(np.arange(10).reshape(5,2),index=[[1,1,1,2,2],['a','a','a','b','b']],
                    columns=['col_1','col_2'])
dframeA

col_1  col_2
1 a      0      1
  a      2      3
  a      4      5
2 b      6      7
  b      8      9

In [35]:
dframeB = DataFrame([[5,10],[15,20]],index = ['a','b'],columns=['col_1','col_2'])
dframeB

col_1  col_2
a      5     10
b     15     20

In [37]:
pd.merge(dframeA,dframeB,how='left')

col_1  col_2
0      0      1
1      2      3
2      4      5
3      6      7
4      8      9

LECTURE 31: Concatenation

In [43]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [45]:
arr1 = np.arange(9).reshape(3,3)

In [46]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
arr2 = np.array([[9,10,11],[12,13,14],[15,16,17]])
arr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [53]:
np.concatenate([arr1,arr2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [54]:
dframe = DataFrame(np.arange(9).reshape(3,3),index = ['a','b','c'],columns=['A','B','C'])

In [55]:
dframe

A  B  C
a  0  1  2
b  3  4  5
c  6  7  8

LECTURE 32: Combining DataFrames

In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [3]:
null = np.nan
dframe_odd = DataFrame({'col_1':[null,null,null,null,null],'col_2':[1,3,5,7,9]})
dframe_odd

col_1  col_2
0    NaN      1
1    NaN      3
2    NaN      5
3    NaN      7
4    NaN      9

In [4]:
dframe_even = DataFrame({'col_1':[0,2,4,6,8],'col_2':[null,null,null,null,null]})
dframe_even

col_1  col_2
0      0    NaN
1      2    NaN
2      4    NaN
3      6    NaN
4      8    NaN

In [7]:
dframe_even.combine_first(dframe_odd)

col_1  col_2
0      0    1.0
1      2    3.0
2      4    5.0
3      6    7.0
4      8    9.0

LECTURE 38: RENAMING INDEXES

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe = DataFrame(np.arange(9).reshape(3,3),index=['LA','NY','MI'],columns=['A','B','C'])
dframe

A  B  C
LA  0  1  2
NY  3  4  5
MI  6  7  8

In [4]:
dframe.rename(index={'LA':'LOS ANGELES','NY':'NEW YORK','MI':'MICHIGAN'},
             columns={'A':'ALPHA','B':'BETA','C':'CHARLIE'})

ALPHA  BETA  CHARLIE
LOS ANGELES      0     1        2
NEW YORK         3     4        5
MICHIGAN         6     7        8

In [5]:
dframe.index.rename(str.lower)

Index(['LA', 'NY', 'MI'], dtype='object', name=<method 'lower' of 'str' objects>)

In [6]:
dframe

A  B  C
LA  0  1  2
NY  3  4  5
MI  6  7  8

In [10]:
dframe.rename(index={'LA':'LOS ANGELES','NY':'NEW YORK','MI':'MICHIGAN'},
             columns={'A':'ALPHA','B':'BETA','C':'CHARLIE'},inplace=True)

In [11]:
dframe

ALPHA  BETA  CHARLIE
LOS ANGELES      0     1        2
NEW YORK         3     4        5
MICHIGAN         6     7        8

In [20]:
dframe1 = DataFrame(np.arange(9).reshape(3,3),index=['LA','NY','MI'],columns=['A','B','C'])
dframe1

A  B  C
LA  0  1  2
NY  3  4  5
MI  6  7  8

In [27]:
dframe1.columns = dframe1.columns.map(str.upper)

In [28]:
dframe1.index = dframe1.index.map(str.upper)

In [29]:
dframe1

A  B  C
<method 'lower' of 'str' objects>         
LA                                 0  1  2
NY                                 3  4  5
MI                                 6  7  8

LECTURE 39: Binning

In [30]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [31]:
numbers = [21,13,19,52,47,69,37]

In [34]:
categories = [10,20,30,40,50,60,70,80,90]

In [35]:
bin1 = pd.cut(numbers,categories)

In [36]:
bin1

[(20, 30], (10, 20], (10, 20], (50, 60], (40, 50], (60, 70], (30, 40]]
Categories (8, interval[int64]): [(10, 20] < (20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 70] < (70, 80] < (80, 90]]

In [37]:
pd.value_counts(bin1)

(10, 20]    2
(60, 70]    1
(50, 60]    1
(40, 50]    1
(30, 40]    1
(20, 30]    1
(80, 90]    0
(70, 80]    0
dtype: int64

In [38]:
bin1.categories

IntervalIndex([(10, 20], (20, 30], (30, 40], (40, 50], (50, 60], (60, 70], (70, 80], (80, 90]],
              closed='right',
              dtype='interval[int64]')

LECTURE 40: Permutations

In [43]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
from numpy.random import randn

In [44]:
dframe = DataFrame(np.arange(16).reshape(4,4),index=[1,2,3,4],columns=['a','b','c','d'])
dframe

a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [49]:
dframe1 = np.random.permutation(4)
dframe1

array([0, 3, 1, 2])

In [52]:
dframe.take(dframe1,axis=1)

a   d   b   c
1   0   3   1   2
2   4   7   5   6
3   8  11   9  10
4  12  15  13  14

In [53]:
dframe.take(dframe1)

a   b   c   d
1   0   1   2   3
4  12  13  14  15
2   4   5   6   7
3   8   9  10  11